### ISSUE TITLE
train_error

### ISSUE THREAD

**Issue by hongge831** [Xiangyu-CAS/Heatmap#4]
line 42, in __getitem__
    img, kpt, center = self.transforms(img, kpt, center)
TypeError: __call__() takes exactly 2 arguments (4 given)
请问这是什么原因

**Comment by Xiangyu-CAS** [comment]
首先请确认你的 self.transforms 来自Mytransforms 而不是 torchvision.transforms

**Comment by hongge831** [comment]
ok，我看看。我是浙大研一小白，能加学长微信交流下吗？如果可以，发微信ID到我的邮箱呗，谢谢学长。yeff@zju.edu.cn

**Comment by hongge831** [comment]
@Xiangyu-CAS 你的代码里写的就是来自torchvision.transforms。。

**Comment by hongge831** [comment]
我把transform换成  Mytransforms后出了这个错误，能指教下吗？
File "/home/whayer/Desktop/YFF/Heatmap-master/dataset_loader.py", line 43, in __getitem__
    img, kpt, center = self.transforms(img, kpt, center)
TypeError: 'module' object is not callable

**Comment by Xiangyu-CAS** [comment]
参考CPM_fpn里面的用法，你用的应该是cpm那个下面的吧，更新了版本没把旧的实验改回来，一切以cpm-fpn为准，你的用法不对，要先new一个实例，而不是把这个module直接赋值，参照cpm_fpn的用法

**Comment by hongge831** [comment]
感谢！
